kind: pipeline
name: default

steps:
- name: build
  image: abitmonn/graal-mill:0.3.5
  commands:
  - mill __.compile
  - mill __.test
  - mill script.assembly  
  - cp out/script/assembly/dest/out.jar hami.jar
  - native-image -jar hami.jar
  